abstract class Strings {
  static const String appName = "the cat clinic";
  static const String titleScreen = "fill the form to continue";
  static const String subTitleScreen = "About you";
  static const String firstName = "first name";
  static const String lastName = "last name";
  static const String yourFirstName = "enter your first name";
  static const String yourLastName = "enter your last name";
  static const String enterPetName = 'enter your pet name';
  static const String phoneNumber = 'phone number';
  static const String enterEmail = 'enter your email';
  static const String notEmail = 'this is not email';
  static const String email = 'email';
  static const String petName = 'pet name';
  static const String breed = 'breed';
  static const String enterBreed = 'enter the breed';
  static const String male = 'Male';
  static const String female = 'Female';
  static const String yourPhoneNumber = "please, enter your phone number";
  static const String continueButton = "CONTINUE";
  static const String gen = 'gender';
  static const String genNotSelected = 'gender not selected';
  static const String foodNotSelected = 'food not selected';
  static const String great = 'successfully';
  static const String save = 'SAVE';
  static const String food1 = "dry food";
  static const String food2 = "wet food";
  static const String food3 = "natural food";
}